Added Polish translation
bartzaalberg/alias pull request #29
Opened 2019-12-13 12:10 UTC by michalzkosmosu

2019-12-13 12:21 UTC, michalzkosmosu commented
What could be wrong?

2019-12-13 17:40 UTC, bartzaalberg commented
Ill check later. Thnx for the MR!

2019-12-15 08:51 UTC, michalzkosmosu commented
Does anyone know what I can do to fix 'The Travis CI build failed'?

2019-12-15 14:57 UTC, bartzaalberg commented
You could copy paste the travis file from 1 one of my other projecten like snaptastic. Should be fine there.

2019-12-21 15:14 UTC, ryonakano requested changes

2019-12-21 15:14 UTC, ryonakano commented on po/extra/pl.po
> +msgstr "skróty klawiszowe;alias;komendy;aliasy;bash"
```suggestion
msgstr "skróty klawiszowe;alias;komendy;aliasy;bash;"
```

Strings for `Keywords` entry in desktop files must end with a semicolon.
([The CI also complains about that](https://travis-ci.org/bartzaalberg/alias/builds/624589947#L387))

2020-01-30 06:00 UTC, bartzaalberg commented on po/extra/pl.po
> +msgstr "com.github.bartzaalberg.alia"
Should be alias

2020-04-15 06:40 UTC, merged